sudo: false
language: ruby
rvm:
  - 2.3.3
  - 2.4.0-preview3
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database patstrial_test;' -U postgres"
  - "bundle exec rake db:migrate"
matrix:
  allow_failures:
    - rvm: 2.4.0-preview3
