sudo: false
language: ruby
rvm:
  - 2.3.4
  - 2.4.1
gemfile: "gems.rb"
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database patstrial_test;' -U postgres"
  - "rails db:migrate"
